clone_depth: 10

version: "{build}"

environment:
  fast_finish: true
  matrix:
    - nodejs_version: "6"
      platform: x86

build: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install yarn -g
  - yarn
  - yarn add global codecov
  - yarn add global eslint
  - yarn add global babel-eslint
  - yarn add global eslint-plugin-node
  - yarn add global eslint-plugin-flowtype@latest
  - yarn add babel-core

test_script:
  - node --version
  - npm --version
  - yarn --version
  - which yarn
  - yarn appveyor:prepare
  - yarn appveyor:lint
  - yarn appveyor:test

cache:
  - node_modules -> appveyor.yml,package.json,yarn.lock
