clone_depth: 10

version: "{build}"

environment:
  fast_finish: true
  matrix:
    - nodejs_version: "8"
      platform: x86

build: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm i -g npm
  - npm i
  - npm ci
  - npm install --global codecov
  - npm install eslint-plugin-node@latest --save-dev

test_script:
  - node --version
  - npm --version
  - which npm
  - npm run appveyor:lint
  - npm run appveyor:test

cache:
  - node_modules -> appveyor.yml,package.json,package-lock.json
