comment: off

parsers:
  javascript:
    enable_partials: yes

coverage:
  status:
    project:
      default:
        threshold: 4%
        if_not_found: success
    patch:
      default:
        if_not_found: success
