"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const defineTest_1 = require("@webpack-cli/utils/defineTest");
const path_1 = require("path");
const dirName = path_1.join(__dirname, "..");
defineTest_1.default(dirName, "commonsChunkPlugin", "commonsChunkPlugin-0");
defineTest_1.default(dirName, "commonsChunkPlugin", "commonsChunkPlugin-1");
defineTest_1.default(dirName, "commonsChunkPlugin", "commonsChunkPlugin-2");
defineTest_1.default(dirName, "commonsChunkPlugin", "commonsChunkPlugin-3");
defineTest_1.default(dirName, "commonsChunkPlugin", "commonsChunkPlugin-4");
defineTest_1.default(dirName, "commonsChunkPlugin", "commonsChunkPlugin-5");
defineTest_1.default(dirName, "commonsChunkPlugin", "commonsChunkPlugin-6a");
defineTest_1.default(dirName, "commonsChunkPlugin", "commonsChunkPlugin-6b");
defineTest_1.default(dirName, "commonsChunkPlugin", "commonsChunkPlugin-6c");
defineTest_1.default(dirName, "commonsChunkPlugin", "commonsChunkPlugin-6d");
defineTest_1.default(dirName, "commonsChunkPlugin", "commonsChunkPlugin-7");
