const packageExists = require('./package-exists');
const cli = packageExists('webpack') ? require('webpack').cli : undefined;

// eslint-disable-next-line node/no-extraneous-require
const devServerFlags = packageExists('webpack-dev-server') ? require('webpack-dev-server/bin/cli-flags').devServer : undefined;

const builtInFlags = [
    // For configs
    {
        name: 'config',
        usage: '--config <path-to-config> | --config <path-to-config> --config <path-to-config>',
        alias: 'c',
        type: String,
        help: 'base',
        multiple: true,
        description: 'Provide path to a webpack configuration file e.g. ./webpack.config.js',
        link: 'https://webpack.js.org/configuration/',
    },
    {
        name: 'config-name',
        usage: '--config-name <name-of-config> | --config-name <name-of-config> --config-name <name-of-config>',
        type: String,
        help: 'verbose',
        multiple: true,
        description: 'Name of the configuration to use',
    },
    {
        name: 'merge',
        usage: '--config <first-config> --config <second-config> --merge',
        alias: 'm',
        type: Boolean,
        help: 'base',
        description: 'Merge two or more configurations using webpack-merge',
        link: 'https://github.com/survivejs/webpack-merge',
    },
    // Complex configs
    {
        name: 'env',
        usage: '--env <variable> | --env <variable> --env <variable=value>',
        type: String,
        help: 'base',
        multipleType: true,
        description: 'Environment passed to the configuration when it is a function',
        link: 'https://webpack.js.org/api/cli/#environment-options',
    },

    // Adding more plugins
    {
        name: 'hot',
        usage: '--hot',
        alias: 'h',
        type: Boolean,
        help: 'base',
        negative: true,
        description: 'Enables Hot Module Replacement',
        negatedDescription: 'Disables Hot Module Replacement',
        link: 'https://webpack.js.org/concepts/hot-module-replacement/',
    },
    {
        name: 'analyze',
        usage: '--analyze',
        type: Boolean,
        help: 'base',
        multiple: false,
        description: 'It invokes webpack-bundle-analyzer plugin to get bundle information',
        link: 'https://github.com/webpack-contrib/webpack-bundle-analyzer',
    },
    {
        name: 'progress',
        usage: '--progress | --progress profile',
        type: [Boolean, String],
        help: 'base',
        description: 'Print compilation progress during build',
    },
    {
        name: 'prefetch',
        usage: '--prefetch <request>',
        type: String,
        help: 'base',
        description: 'Prefetch this request',
        link: 'https://webpack.js.org/plugins/prefetch-plugin/',
    },

    // Help and versions
    {
        name: 'help',
        usage: '--help',
        type: [Boolean, String],
        help: 'base',
        description: 'Outputs list of supported flags',
    },
    {
        name: 'version',
        usage: '--version | --version <external-package>',
        alias: 'v',
        type: Boolean,
        help: 'base',
        description: 'Get current version',
    },

    // Output options
    {
        name: 'json',
        usage: '--json | --json <path-to-stats-file>',
        type: [String, Boolean],
        help: 'base',
        alias: 'j',
        description: 'Prints result as JSON or store it in a file',
    },
    {
        name: 'color',
        usage: '--color',
        type: Boolean,
        help: 'base',
        negative: true,
        description: 'Enable colors on console',
        negatedDescription: 'Disable colors on console',
    },

    // For webpack@4
    {
        name: 'entry',
        usage: '--entry <path-to-entry-file> | --entry <path> --entry <path>',
        type: String,
        multiple: true,
        help: 'base',
        description: 'The entry point(s) of your application e.g. ./src/main.js',
        link: 'https://webpack.js.org/concepts/#entry',
    },
    {
        name: 'output-path',
        usage: '--output-path <path-to-output-directory>',
        alias: 'o',
        type: String,
        help: 'verbose',
        description: 'Output location of the file generated by webpack e.g. ./dist/',
        link: 'https://webpack.js.org/configuration/output/#outputpath',
    },
    {
        name: 'target',
        usage: '--target <value> | --target <value> --target <value>',
        alias: 't',
        type: String,
        help: 'base',
        multiple: cli !== undefined,
        description: 'Sets the build target e.g. node',
        link: 'https://webpack.js.org/configuration/target/#target',
    },
    {
        name: 'devtool',
        usage: '--devtool <value>',
        type: String,
        help: 'base',
        negative: true,
        alias: 'd',
        description: 'Determine source maps to use',
        negatedDescription: 'Do not generate source maps',
        link: 'https://webpack.js.org/configuration/devtool/#devtool',
    },
    {
        name: 'mode',
        usage: '--mode <development | production | none>',
        help: 'base',
        type: String,
        description: 'Defines the mode to pass to webpack',
        link: 'https://webpack.js.org/concepts/#mode',
    },
    {
        name: 'name',
        usage: '--name',
        type: String,
        help: 'base',
        description: 'Name of the configuration. Used when loading multiple configurations.',
        link: 'https://webpack.js.org/configuration/other-options/#name',
    },
    {
        name: 'stats',
        usage: '--stats | --stats <value>',
        type: [String, Boolean],
        negative: true,
        help: 'base',
        description: 'It instructs webpack on how to treat the stats e.g. verbose',
        negatedDescription: 'Disable stats output',
        link: 'https://webpack.js.org/configuration/stats/#stats',
    },
    {
        name: 'watch',
        usage: '--watch',
        type: Boolean,
        help: 'base',
        negative: true,
        alias: 'w',
        description: 'Watch for files changes',
        negatedDescription: 'Do not watch for file changes',
        link: 'https://webpack.js.org/configuration/watch/',
    },
];

// Extract all the flags being exported from core.
// A list of cli flags generated by core can be found here https://github.com/webpack/webpack/blob/master/test/__snapshots__/Cli.test.js.snap
const coreFlags = cli
    ? Object.entries(cli.getArguments()).map(([flag, meta]) => {
          if (meta.simpleType === 'string') {
              meta.type = String;
              meta.usage = `--${flag} <value>`;
          } else if (meta.simpleType === 'number') {
              meta.type = Number;
              meta.usage = `--${flag} <value>`;
          } else {
              meta.type = Boolean;
              meta.negative = !flag.endsWith('-reset');
              meta.usage = `--${flag}`;
          }

          const inBuiltIn = builtInFlags.find((builtInFlag) => builtInFlag.name === flag);

          if (inBuiltIn) {
              return { ...meta, name: flag, group: 'core', ...inBuiltIn };
          }

          return { ...meta, name: flag, group: 'core' };
      })
    : [];
const flags = []
    .concat(builtInFlags.filter((builtInFlag) => !coreFlags.find((coreFlag) => builtInFlag.name === coreFlag.name)))
    .concat(coreFlags);

const isCommandUsed = (args) =>
    commands.find((cmd) => {
        return args.includes(cmd.name) || args.includes(cmd.alias);
    });

const commands = [
    {
        packageName: '@webpack-cli/migrate',
        name: 'migrate <config-path> [new-config-path]',
        alias: 'm',
        type: String,
        usage: 'migrate <config-path> [new-config-path]',
        description: 'Migrate a configuration to a new version',
        flags: [],
    },
    {
        packageName: '@webpack-cli/serve',
        name: 'serve',
        alias: 's',
        scope: 'external',
        type: String,
        usage: 'serve [options]',
        description: 'Run the webpack Dev Server',
        flags: [
            ...(devServerFlags &&
                devServerFlags.reduce((cliArgs, { name, type, describe }) => {
                    return [...cliArgs, { name, type, description: describe }];
                }, [])),
            ...flags,
        ],
    },
];

module.exports = {
    commands,
    cli,
    flags,
    isCommandUsed,
};
