import { defaultConfig } from "./constants";

/**
 *
 * Utility function to check if the user config is same as default.
 *
 * @param	{Object[]} initConfig 	- config generated by the user.
 * @returns {Boolean} - Whether the default config is used or not.
 */

export default function checkDefaults(initConfig: Record<string, any>): boolean {
	return initConfig.every((property: string): boolean => {
		const propertyName = Object.keys(property)[0];
		return defaultConfig[propertyName] === property[propertyName];
	});
}
