/**
 *
 * Utility function to check if the user config is same as default.
 *
 * @param	{Object[]} initConfig 	- config generated by the user
 * @returns {Boolean} - Whether the default condif is used or not
 */

export default function checkDefaults(initConfig: Object[]) {
  // This is the default prompts selections generated on picking default options.
  const defaultConfig = {
		babelConfirm: true,
		entryOption: "\'\'",
		entryType: false,
		outputType: "",
		stylingType: "No",
  };

  return initConfig.every((property) => {
		const propertyName = Object.keys(property)[0];
		return defaultConfig[propertyName] === property[propertyName];
  });
}
